### ISSUE TITLE
Corrupted Images

### ISSUE THREAD

**Issue by NicholasMoratelli** [Top34051/colorswap#1]
Hi! 

I would like to use your dataset but I am having problems loading images. They seem to be corrupted both by downloading them from Google Drive and huggingface.

**Comment by TristanThrush** [comment]
Thanks for your interest! What errors do you see when trying to load the images? Or if the issue is that images just don't look right, can you post examples of them here?

**Comment by TristanThrush** [comment]
I'm curious what happens when you do this?

```
$ huggingface-cli login
$ python
>>> from datasets import load_dataset
>>> dataset = load_dataset("stanfordnlp/colorswap", use_auth_token=True)
>>> dataset["train"][0]["image_1"].open()
```

**Comment by TristanThrush** [comment]
(before doing this, you also have to click to access the dataset on the huggingface dataset page while logged into your account)

**Comment by TristanThrush** [comment]
Closing due to no response
